<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__1</name>
   <tag></tag>
   <elementGuidId>70b69979-c4d7-418b-82c7-4b7d1106509d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d8e4db26-e27a-420f-86db-5ae70f91b553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
      <webElementGuid>50e4fb51-94a5-4f1d-9f52-06c3d1fa78b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>20f3b7be-5ba8-48a0-a3e4-b1fbbd6b7e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7b21bd7c-3647-483c-be7f-595d136192d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>หเ</value>
      <webElementGuid>77a5217c-e929-4e6c-ba16-20115315a9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]/textarea[@class=&quot;rounded&quot;]</value>
      <webElementGuid>ad52caf2-87ce-4a8f-9642-f106fad2f4c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='']</value>
      <webElementGuid>713db613-26bc-4f36-98ff-01a832718605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/textarea</value>
      <webElementGuid>93afd820-f7a8-461b-95f8-74f8369a1e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แจ้งรายละเอียดปัญหา'])[1]/following::textarea[1]</value>
      <webElementGuid>142c0250-8518-416a-b445-f1d645342d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รูปภาพสิ่งของชำรุด'])[1]/following::textarea[1]</value>
      <webElementGuid>59ec16b1-0aee-468e-82d9-8b130bb08e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยืนยัน'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5d63414a-ef56-4e87-8e57-6d0b2b1111a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='หเ']/parent::*</value>
      <webElementGuid>7348a8c3-b6f3-4bc3-82fd-45be099c990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bf5cbb48-38b7-43f1-9cc4-cc67a819857f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'หเ' or . = 'หเ')]</value>
      <webElementGuid>69221956-4cbf-4081-bdde-d60271820dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
