<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_-</name>
   <tag></tag>
   <elementGuidId>a076ccc0-8aa5-4562-bdc3-3b1528c64bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.c2.col > form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>8cc8cc1a-7281-408a-804d-2f29a35e56cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน</value>
      <webElementGuid>1abcc967-5595-4904-b687-0ee83bac5333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]</value>
      <webElementGuid>9c3ef2de-4190-44cf-828d-5b6891912c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form</value>
      <webElementGuid>2090bf02-53fa-48ad-95f7-7ea6c2b65a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชั้นปี'])[1]/following::form[1]</value>
      <webElementGuid>78bda010-aeee-4c0c-b839-b874fa8261b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสนิสิต'])[1]/following::form[1]</value>
      <webElementGuid>35a424c5-d4a1-4482-901e-c18e1b86c30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form</value>
      <webElementGuid>87c89d39-9cff-4d92-a8cd-a7576ece6500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน' or . = 'แจ้งปัญหาชื่อ-นามสกุลหอพักห้องพักรูปภาพสิ่งของชำรุดแจ้งรายละเอียดปัญหายืนยัน')]</value>
      <webElementGuid>0b113332-026d-415d-a9e3-f0d8aac1c63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
